version: '3.8'

services:
  # MySQL 数据库
  database:
    image: mysql:8.0
    container_name: training_system_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: training_system
      MYSQL_USER: training_user
      MYSQL_PASSWORD: training_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: training_system_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # 应用服务（开发环境使用）
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: training_system_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: "mysql://training_user:training_password@database:3306/training_system"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: "dev-jwt-secret-key"
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - database
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

volumes:
  mysql_data:
  redis_data: 